[menu]
music = "alacritty -e mpv --shuffle --loop-playlist ~/Music/{music, nightcore, old}/*"
steam = true
heroic = true
prismlauncher = true
keepassxc = true
element = "element-desktop"
calibre = true

[config.dmenu]
prompt = "common:"
