[menu]
poweroff = "systemctl poweroff"
reboot = "systemctl reboot"
suspend = "slock & systemctl suspend"
hibernate = { run = "slock & systemctl hibernate", group = -1 }


[config.dmenu]
prompt = "system:"
