[menu]
music = { run = "alacritty -e mpv --shuffle --loop-playlist ~/music", group = 1 }
steam = { run = "steam", group = 1 }
minecraft = "multimc"

[config.dmenu]
prompt = "common:"
font = "Hack Nerd Font:size=16"
background = "#002b36"
foreground = "#839496"
selected-background = "#268bd2"
selected-foreground = "#002b36"
