entries = [
    "poweroff",
    "reboot",
]

[menu]
suspend = "slock & systemctl suspend"
"restart xmonad" = { run = "xmonad --recompile; xmonad --restart", group = -1 }

[config.dmenu]
prompt = "system:"
font = "Hack Nerd Font:size=16"
background = "#002b36"
foreground = "#839496"
selected-background = "#268bd2"
selected-foreground = "#002b36"
