entries = [
    "poweroff",
    "reboot",
]

[menu]
suspend = "slock & systemctl suspend"

[config.dmenu]
prompt = "system:"
font = "Hack Nerd Font:size=12"
background = "#101010"
foreground = "#f0f0f0"
selected-background = "#00c0ff"
selected-foreground = "#000000"
