snippet_support = false
verbosity = 2

# Semantic tokens support
# See https://github.com/microsoft/vscode-languageserver-node/blob/8c8981eb4fb6adec27bf1bb5390a0f8f7df2899e/client/src/semanticTokens.proposed.ts#L288
# for token/modifier types.

[semantic_tokens]
type = "type"
variable = "variable"
namespace = "module"
function = "function"
string = "string"
keyword = "keyword"
operator = "operator"
comment = "comment"

[semantic_token_modifiers]
documentation = "documentation"
readonly = "default+d"

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 0

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"

# [language.rust.initialization_options]
# # If you get 'unresolved proc macro' warnings, you have two options
# # 1. The safe choice is two disable the warning:
# diagnostics.disabled = ["unresolved-proc-macro"]
# # 2. Or you can opt-in for proc macro support
# procMacro.enable = true
# cargo.loadOutDirsFromCheck = true
# # See https://github.com/rust-analyzer/rust-analyzer/issues/6448
